[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
bank_app = "6zCwGUboqLEHq93tsGTvMmZ3xTnyK4dsT8qXRcNVWRRj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
